### ISSUE TITLE
[Android/iOS] Local watch faces not supported by the SDK/firmware

### ISSUE THREAD

**Issue by karran-radixeng** [omatheusv/SOPlifeultra#2]
Just like with Sports Call, we would like to be able to set the existing watch faces that come built-in the firmware from the app. E.g. being able to switch from the first built-in watch face to the third built-in watch face through the app/SDK instead of doing so manually through the watch. We also need to be able to know the valid names/indexes to show to the user in the app.

However, that's not possible on both OSes.

On iOS, we haven't been able to find any methods on the docs or in the SDK related to getting a list of built-in watch faces or related to setting them via the SDK.

On Android, there seem to be methods related to that (2.43 Local Watch Face Setting) but they seem to be unsupported, since `DeviceMode.isHasFunction_8(DeviceMode.IS_SUPPORT_LOCAL_WATCH_FACE)` returns `false`.

**Comment by Jessica2024SOP** [comment]
The chipset of B07pro is RTL8763EWE. The chipset of A21 are Actions. The SDK logic are totally different. The B07pro SDK not support to switch built-in watch face thought APP/SDK.
