### ISSUE TITLE
[Android/iOS] A07 Pro receives notifications even when Do Not Disturb is on

### ISSUE THREAD

**Issue by karran-radixeng** [omatheusv/SOPlifeultra#4]
On both operating systems, even after enabling the "do not disturb" functionality, the watch still receives notifications.

On Android we receive notifications for all apps, while on iOS we've only managed to reproduce the issue for WhatsApp so far.

[logs-android.txt](https://github.com/user-attachments/files/16163969/logs-android.txt)
[logs-ios.txt](https://github.com/user-attachments/files/16163970/logs-ios.txt)

Both text files above show all the logs printed in the following process, for both systems:

1. Watch is paired.
2. Notifications are enabled.
3. Do not disturb is enabled.
4. WhatsApp notification is received by the phone and is also shown on the watch.

**Comment by Jessica2024SOP** [comment]
Pls kindly share operate video and complete log which included below two aspects: 

1. When user set the DND, and was it set correctly?
2. After setting, did the APP call and send the APP push command?

Besides, we also need confirm which APP you're using , GloryFit or Technos's APP ?  If using Technos's APP, pls confirm if the APP have developed DND.  DND has been set locally on watch, so no need to repeat develop in APP.

**Comment by karran-radixeng** [comment]
I've confirmed that the bug happened when turning it on/off from the SDK. As said during the meeting, DND can only be enabled/disabled from the watch, so I'm closing this issue.

If we find any problems with DND enabled/disabled from the watch, I'll create a separate issue.
